Repository AntonArtomovNM/KCAA, pull requests merged in 2021-11, with the labels that each got.

#12 feat: Added game object builder and factories
  KCAA/KCAA.csproj
  KCAA/Models/Card.cs
  KCAA/Models/Cards/Card.cs
  KCAA/Models/Cards/CardNames.cs
  KCAA/Models/Characters/Character.cs
  KCAA/Models/Characters/CharacterNames.cs
  KCAA/Models/GameObject.cs
  KCAA/Services/Builders/GameObjectBuilder.cs
  KCAA/Services/Factories/CardFactory.cs
  KCAA/Services/Factories/CharacterFactory.cs
  KCAA/Services/Interfaces/IGameObjectBuilder.cs
  KCAA/Services/Interfaces/IGameObjectFactory.cs
  KCAA/Settings/GameSettings/CardSettings.json
  KCAA/Settings/GameSettings/CharacterSettings.json
  KCAA/Settings/GameSettings/GameSettings.cs
  KCAA/Startup.cs
  KCAA/appsettings.Development.json
  KCAA/appsettings.json
Labels: core

#14 feat: Added basic card and character settings, added game action class
  KCAA/Models/GameAction.cs
  KCAA/Settings/GameSettings/CardSettings.json
  KCAA/Settings/GameSettings/CharacterSettings.json
  docs/High-level diagram.drawio
Labels: core, infrastructure

#13 feat: Added MongoDb connection
  KCAA/Extensions/HealthChecks.cs
  KCAA/KCAA.csproj
  KCAA/Models/Cards/CardNames.cs
  KCAA/Models/MongoDB/ActiveCardDto.cs
  KCAA/Models/MongoDB/CharacterDto.cs
  KCAA/Models/MongoDB/CharacterEffect.cs
  KCAA/Models/MongoDB/CharacterStatus.cs
  KCAA/Models/MongoDB/MongoDbObject.cs
  KCAA/Models/MongoDB/Player.cs
  KCAA/Models/MongoDB/Room.cs
  KCAA/Models/MongoDB/RoomStatus.cs
  KCAA/Properties/launchSettings.json
  KCAA/Services/Interfaces/IPlayerProvider.cs
  KCAA/Services/Interfaces/IRoomProvider.cs
  KCAA/Services/Providers/MongoDbProviderBase.cs
  KCAA/Services/Providers/PlayerProvider.cs
  KCAA/Services/Providers/RoomProvider.cs
  KCAA/Services/TelegramApi/TelegramUpdateHandler.cs
  KCAA/Settings/MongoDBSettings.cs
  KCAA/Startup.cs
  KCAA/appsettings.json
  docs/ER diagram.drawio
  docs/UML-diagram.drawio
Labels: infrastructure

#16 doc: Added component diagram
  docs/ComponentsDiagram.drawio
  docs/ComponentsDiagram.drawio.png
Labels: documentation

#17 Telegram "create_lobby" and "join_lobby" commands
  KCAA/Extensions/TelegramBotClientExtentions.cs
  KCAA/KCAA.csproj
  KCAA/Models/MongoDB/Lobby.cs
  KCAA/Models/MongoDB/LobbyStatus.cs
  KCAA/Models/MongoDB/Player.cs
  KCAA/Models/MongoDB/Room.cs
  KCAA/Services/Factories/TelegramHandlerFactory.cs
  KCAA/Services/Interfaces/ILobbyProvider.cs
  KCAA/Services/Interfaces/IPlayerProvider.cs
  KCAA/Services/Interfaces/IRoomProvider.cs
  KCAA/Services/Interfaces/ITelegramHandlerFactory.cs
  KCAA/Services/Interfaces/ITelegramUpdateGateway.cs
  KCAA/Services/Interfaces/ITelegramUpdateHandler.cs
  KCAA/Services/Providers/LobbyProvider.cs
  KCAA/Services/Providers/PlayerProvider.cs
  KCAA/Services/Providers/RoomProvider.cs
  KCAA/Services/TelegramApi/BotMessages.cs
  KCAA/Services/TelegramApi/KeyboardAction.cs
  KCAA/Services/TelegramApi/TelegramUpdateGateway.cs
  KCAA/Services/TelegramApi/TelegramUpdateHandlers/TelegramMessageHandler.cs
  KCAA/Services/TelegramApi/TelegramUpdateHandlers/TelegramMyChatMemberHandler.cs
  KCAA/Services/TelegramApi/TelegramUpdateHandlers/TelegramUnknownUpdateHandler.cs
  KCAA/Settings/GameSettings/GameSettings.cs
  KCAA/Settings/MongoDBSettings.cs
  KCAA/Settings/TelegramSettings.cs
  KCAA/Startup.cs
  KCAA/appsettings.Development.json
  KCAA/appsettings.json
  docs/ER diagram.drawio
  docs/ER-diagram.png
  docs/High-level-diagram.png
  docs/UML-diagram.drawio
  docs/UML-diagram.png
Labels: core

#18 Added deployment diagram
  docs/DeploymentDiagram.drawio
  docs/DeploymentDiagram.png
  docs/README.md
Labels: documentation

#19 Diagram update
  KCAA/Services/Builders/GameObjectBuilder.cs
  KCAA/Services/Interfaces/IGameObjectBuilder.cs
  KCAA/Startup.cs
  KCAA/appsettings.json
  docs/ComponentsDiagram.png
  docs/README.md
  docs/SequenceDiagram.drawio
  docs/SequenceDiagram.png
  docs/UML-diagram.drawio
  docs/UML-diagram.png
Labels: documentation

#15 Expanded district card and character settings
  KCAA/Models/Cards/CardNames.cs
  KCAA/Models/Characters/CharacterNames.cs
  KCAA/Settings/GameSettings/CardSettings.json
  KCAA/Settings/GameSettings/CharacterSettings.json
Labels: core

#20 Implemented telegram depictions of cards and characters
  KCAA/Extensions/TelegramBotClientExtentions.cs
  KCAA/Services/TelegramApi/TelegramUpdateHandlers/TelegramMessageHandler.cs
  KCAA/appsettings.json
Labels: core
